set nocp
set rtp=../
set laststatus=2

" colors
hi StatusLine         guifg=#a59f85 guibg=#49483e gui=none ctermfg=20     ctermbg=19  cterm=none
hi StatusLineNC       guifg=#75715e guibg=#383830 gui=none ctermfg=08     ctermbg=18  cterm=none
hi ModestatusMode     guifg=Yellow  guibg=#49483e gui=bold ctermfg=Yellow ctermbg=19  cterm=bold
hi ModestatusFilename guifg=#a59f85 guibg=#49483e gui=bold ctermfg=20     ctermbg=19  cterm=bold
hi ModestatusModified guifg=Red     guibg=#49483e gui=bold ctermfg=Red    ctermbg=19  cterm=bold
hi ModestatusError    guifg=White   guibg=#af0000 gui=none ctermfg=White  ctermbg=124 cterm=none
hi ModestatusWarning  guifg=Black   guibg=#dfaf00 gui=none ctermfg=Black  ctermbg=178 cterm=none

" enable extensions
call modestatus#extensions#enable('core')
call modestatus#extensions#enable('loclist')

" the active/inactive statusline layout
let g:modestatus#statusline = {
    \ 'active': {
    \     'left': [
    \         'line_percent',
    \         'position',
    \         'mode',
    \         'filename',
    \         'modified',
    \         'readonly',
    \         'paste',
    \         'filetype',
    \         'encoding',
    \         'fileformat',
    \         'loclist_errors',
    \         'loclist_warnings'
    \     ],
    \     'right': [
    \     ]
    \ },
    \ 'inactive': {
    \     'left': [
    \         'filename',
    \         'modified',
    \         'readonly',
    \         'filetype',
    \         'encoding',
    \         'fileformat',
    \         'loclist_errors',
    \         'loclist_warnings'
    \     ],
    \     'right': [
    \     ]
    \ }}

" filename overrides, part of the core extension
let g:modestatus#extensions#core#filename_override = {
    \     '[No Name]': ''
    \ }

" filename type-based overrides, part of the core extension
let g:modestatus#extensions#core#filetype_override = {
    \     'qf': '',
    \     'undotree': 'UndoTree'
    \ }

" setup general statusline part options
call modestatus#options#add('filename', {
    \ 'active': {
    \     'color': 'ModestatusFilename'
    \ }})
call modestatus#options#add('mode', {
    \ 'active': {
    \     'color': 'ModestatusMode',
    \     'format': '‹%s›'
    \ }})
call modestatus#options#add('modified', {
    \ 'active': {
    \     'color': 'ModestatusModified'
    \ }})
call modestatus#options#add('readonly', {
    \ 'active': {
    \     'color': 'ModestatusModified'
    \ }})
call modestatus#options#add('paste', {
    \ 'active': {
    \     'color': 'ModestatusModified'
    \ }})
call modestatus#options#add('filetype', {
    \ 'active': {
    \     'format': '[%s]'
    \ },
    \ 'inactive': {
    \     'format': '[%s]'
    \ }})
call modestatus#options#add('encoding', {
    \ 'active': {
    \     'format': '[%s:',
    \     'separator': ''
    \ },
    \ 'inactive': {
    \     'format': '[%s:',
    \     'separator': ''
    \ }})
call modestatus#options#add('fileformat', {
    \ 'active': {
    \     'format': '%s]'
    \ },
    \ 'inactive': {
    \     'format': '%s]'
    \ }})
call modestatus#options#add('loclist_errors', {
    \ 'active': {
    \     'color': 'ModestatusError',
    \     'format': ' %s ',
    \     'separator': ''
    \ },
    \ 'inactive': {
    \     'separator': ''
    \ }})
call modestatus#options#add('loclist_warnings', {
    \ 'active': {
    \     'color': 'ModestatusWarning',
    \     'format': ' %s ',
    \     'separator': ''
    \ },
    \ 'inactive': {
    \     'separator': ''
    \ }})
